### ISSUE TITLE
[JOSS Review] README file

### ISSUE THREAD

**Issue by kbwestfall** [tvwenger/bayes_spec#38] opened 2024-10-04 18:10 UTC
- If I just place the code in the quick-start section into a file and execute it::

       % python quick_start.py

   I get an error: `BrokenPipeError: [Errno 32] Broken pipe`.  The error goes away if I put the code in a main function; i.e.::

        def main():
            # Quick start code

        if __name__ == '__main__':
            main()

 - The "documentation and tutorials" link in the quick start links to a badge.

 - Is there any specific reason you haven't used astropy's `specutils.Spectrum1D` object instead of your `SpecData` object?

**Comment by tvwenger** [comment] 2024-10-07 15:47
@kbwestfall Thanks for testing!

> If I just place the code in the quick-start section into a file and execute it

I am not able to reproduce this `BrokenPipeError`. I suspect this is likely an OS-dependent. Are you running on Windows by chance? I understand that Windows often requires multiprocessing code to be wrapped in `if __name__ == "__main__":`.

> The "documentation and tutorials" link in the quick start links to a badge.

Nice catch!

> Is there any specific reason you haven't used astropy's `specutils.Spectrum1D` object instead of your `SpecData` object?

Two reasons:
1. Reduce dependency overhead
2. Allow for future `pytensor` operations on data

I would prefer not to include `astropy` in the dependency tree.

**Comment by tvwenger** [comment] 2024-10-07 17:19
Thanks for the info! Indeed, I think this is just a case of OS-dependent `if __name__ == "__main__"` requirements.

I've updated the bad documentation link and will close this issue. Thanks for reporting!

**Closed by tvwenger** 2024-10-07 17:19 UTC
Labels: documentation
